/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.User;
import util.DatabaseConnector;

/**
 *
 * @author anmolvalecha
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    private ViewPanel viewPanel;
    public CreatePanel(ViewPanel viewPanel) {
        this.viewPanel = viewPanel;
        initComponents();
    }
public void setViewPanel(ViewPanel viewPanel) {
        this.viewPanel = viewPanel;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();

        nameLabel.setText("Name");

        ageLabel.setText("Age");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ageLabel)
                                .addGap(136, 136, 136)
                                .addComponent(ageTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addGap(124, 124, 124)
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(submitButton)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ageLabel)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(submitButton)
                .addContainerGap(216, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:String name = nameTextField.getText();
   
        int age = Integer.parseInt(ageTextField.getText());

    //Create a User object
   // User user = new User();
   // user.setName(name);
   // user.setAge(age);
// Use database connector to save the User object to the database
 /*
    try {
        DatabaseConnector.saveUserToDatabase(user);
        System.out.println("User saved to database successfully!");
    } catch (Exception e) {
        System.err.println("Error saving user to database: " + e.getMessage());
        e.printStackTrace();
    }
    */
        /*User newUser = new User();
    try {
        newUser.setAge(Integer.parseInt(ageTextField.getText()));
        newUser.setName(nameTextField.getText());
       
        //insert into db
        DatabaseConnector.addUser(newUser);
        JOptionPane.showMessageDialog(null, "User Registered Successfully", "Registration is succesfull", JOptionPane.INFORMATION_MESSAGE);
        cleanup();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
    }*/
                                                
    User newUser = new User();
    try {
        newUser.setAge(Integer.parseInt(ageTextField.getText()));
        newUser.setName(nameTextField.getText());
        // Insert into db
        DatabaseConnector.addUser(newUser);
        JOptionPane.showMessageDialog(null, "User Registered Successfully", "Registration is successful", JOptionPane.INFORMATION_MESSAGE);
        cleanup();
        viewPanel.refreshTable();
        //populateTable();  // Add this line to refresh the table in the ViewPanel
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }


        
    }//GEN-LAST:event_submitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables

 
public void cleanup() {
    nameTextField.setText("");
    ageTextField.setText("");
}
}